//
// Created by e22-watson on 24/01/2020.
//

#pragma once

#ifndef THE_SHINING_GAME_PROJECT_237_SCENEIDS_H
#  define THE_SHINING_GAME_PROJECT_237_SCENEIDS_H

#endif // THE_SHINING_GAME_PROJECT_237_SCENEIDS_H

enum SceneID
{
  CLOSE_GAME = 0,
  MAIN_MENU = 1,
  LEVEL_EASY = 2,
  LEVEL_MEDIUM = 3,
  LEVEL_HARD = 4,
  LORE_MENU = 5,
  INSTRUCTIONS_MENU = 6,
};