//
// Created by e22-watson on 13/01/2020.
//
#pragma once

#ifndef THE_SHINING_GAME_PROJECT_237_LEVELDIFFICULTY_H
#  define THE_SHINING_GAME_PROJECT_237_LEVELDIFFICULTY_H

#endif // THE_SHINING_GAME_PROJECT_237_LEVELDIFFICULTY_H

enum LevelDifficulty
{
  NO_DIFFICULTY = -1,
  EASY = 0,
  MEDIUM = 1,
  HARD = 2
};