//
// Created by Kirsten on 19/01/2020.
//

#ifndef THE_SHINING_GAME_PROJECT_237_PLAYER_H
#define THE_SHINING_GAME_PROJECT_237_PLAYER_H

class Player
{
};

#endif // THE_SHINING_GAME_PROJECT_237_PLAYER_H
